# lecture

## 4.1 여러개의 입력

- 기존의 식인 H(x) = Wx + b가 H(x1,x2,x3,...,xn) = w1x1 + w2x2 + w3x3 + wnxn + b로 변한다.
- cost도 마찬가지로  x자리에 여러개의 x값을 모두 넣으면 된다.
- 하지만 이 식을 쓰게 되면 큰값은 너무 길어지기 때문에 이 때 사용하는 것이 matrix(행렬) 이다. 결과는 H(X) = XW로 변한다.(행렬 곱할 때 코드의 효율을 위해 X, W위치가 정해져 있고 이로 인해 자리가 서로 바뀐 것에 유의)


# programming

## 4.2 matrix

- matrix를 사용하지 않고 리스트로 수 대입

In [12]:
import tensorflow as tf
x1_data = [73.,93., 90., 85., 73.]
x2_data = [88.,97., 83., 99., 83.]
x3_data = [78.,99., 79., 83., 91.]
y_data = [134.,185., 177., 135.,155.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'weight1')
w2 = tf.Variable(tf.random_normal([1]), name = 'weight2')
w3 = tf.Variable(tf.random_normal([1]), name = 'weight3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for step in range(200):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict = {x1: x1_data, x2:x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  13693.9 
Prediction:
 [ 23.19325066  50.25239944  74.0671463   36.6867485   21.68109322]
10 Cost:  218.005 
Prediction:
 [ 129.99891663  179.21897888  186.16415405  155.8644104   132.16819763]
20 Cost:  214.473 
Prediction:
 [ 130.2540741   179.61213684  186.3258667   156.05186462  132.65834045]
30 Cost:  211.091 
Prediction:
 [ 130.2350769   179.67385864  186.20074463  155.934021    132.86347961]
40 Cost:  207.77 
Prediction:
 [ 130.21540833  179.73422241  186.07614136  155.81640625  133.0660553 ]
50 Cost:  204.507 
Prediction:
 [ 130.19581604  179.7940979   185.95277405  155.69967651  133.26679993]
60 Cost:  201.302 
Prediction:
 [ 130.17634583  179.85350037  185.83068848  155.5839386   133.46574402]
70 Cost:  198.154 
Prediction:
 [ 130.15687561  179.91238403  185.70980835  155.46910095  133.66285706]
80 Cost:  195.063 
Prediction:
 [ 130.13754272  179.9708252   185.59017944  155.35525513  133.85823059]
90 Cost:  192.026 
Prediction:
 [ 130.11828613  180.02879333  185.47175

- matrix를 이용하여 구하기

In [13]:
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [195.], [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape = [None, 1])

w = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

hypothesis = tf.matmul(X, w) + b
cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(200):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  591.485 
Prediction:
 [[ 134.07846069]
 [ 155.77377319]
 [ 156.10374451]
 [ 171.12686157]
 [ 116.67979431]]
10 Cost:  14.5001 
Prediction:
 [[ 155.31282043]
 [ 181.32125854]
 [ 181.26296997]
 [ 198.52545166]
 [ 136.17173767]]
20 Cost:  14.4269 
Prediction:
 [[ 155.36372375]
 [ 181.40779114]
 [ 181.33509827]
 [ 198.60481262]
 [ 136.24336243]]
30 Cost:  14.3594 
Prediction:
 [[ 155.35058594]
 [ 181.41723633]
 [ 181.33132935]
 [ 198.60150146]
 [ 136.25619507]]
40 Cost:  14.2923 
Prediction:
 [[ 155.33728027]
 [ 181.42642212]
 [ 181.3273468 ]
 [ 198.59796143]
 [ 136.26879883]]
50 Cost:  14.2255 
Prediction:
 [[ 155.32398987]
 [ 181.43559265]
 [ 181.32336426]
 [ 198.59443665]
 [ 136.28138733]]
60 Cost:  14.1591 
Prediction:
 [[ 155.3107605 ]
 [ 181.44473267]
 [ 181.31939697]
 [ 198.59089661]
 [ 136.29394531]]
70 Cost:  14.093 
Prediction:
 [[ 155.29756165]
 [ 181.45385742]
 [ 181.31544495]
 [ 198.58738708]
 [ 136.30645752]]
80 Cost:  14.0274 
Prediction:
 [[ 155.28439331]
 [ 181.46

## 4.3 데이터를 파일로 받아와서 구하기

- 자료를 로드해서 결과를 구하기
- slicing : 범위를 지정해서 그에 해당하는 값들을 출력한다.

In [16]:
import numpy as np
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype = np.float32)
x_data = xy[:, 0:-1]  # x축으로 마지막 하나의 데이터를 제외한 모든 데이터를 가져오기
y_data = xy[:, [-1]]  # y축으로 마지막 줄을 제외하고 모든 데이터 가져오기

- batch : 자료를 가져올 수 있게 해주는 기능을 한다.
- batch_size : 한번에 가져오는 데이터 개수

In [ ]:
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size = 10)
sess = tf.Session()

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess = sess, coord = coord)
for step in range(200):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    
coord.request_stop()
coord.join(threads)

In [25]:
import tensorflow as tf
tf.set_random_seed(777)

filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

for step in range(200):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

coord.request_stop()
coord.join(threads)

0 Cost:  1275.78 
Prediction:
 [[ 115.65512085]
 [ 143.58433533]
 [ 138.97602844]
 [ 152.29519653]
 [ 110.01032257]
 [  83.37097931]
 [ 114.32733917]
 [  85.01467133]
 [ 136.54585266]
 [ 129.15187073]]
10 Cost:  8.31698 
Prediction:
 [[ 151.48542786]
 [ 186.64413452]
 [ 181.40596008]
 [ 198.50622559]
 [ 142.84785461]
 [ 107.58267212]
 [ 148.92170715]
 [ 110.66627502]
 [ 176.78913879]
 [ 166.43006897]]
20 Cost:  8.97903 
Prediction:
 [[ 151.73252869]
 [ 186.92933655]
 [ 181.69303894]
 [ 198.81907654]
 [ 143.06227112]
 [ 107.73969269]
 [ 149.15950012]
 [ 110.84798431]
 [ 177.0532074 ]
 [ 166.67407227]]
30 Cost:  8.95826 
Prediction:
 [[ 151.73947144]
 [ 186.92590332]
 [ 181.69570923]
 [ 198.82220459]
 [ 143.05654907]
 [ 107.73439789]
 [ 149.16546631]
 [ 110.85778809]
 [ 177.04751587]
 [ 166.66819763]]
40 Cost:  8.93255 
Prediction:
 [[ 151.74478149]
 [ 186.92053223]
 [ 181.69644165]
 [ 198.82321167]
 [ 143.04933167]
 [ 107.72803497]
 [ 149.16983032]
 [ 110.86643219]
 [ 177.04000854]
 [ 1