# programming

## 8.1 Tensor Manipulation

- ndim : 몇차원인지(rank)
- shape : 배열의 모양
- axis : 축이라고 하고 가장 바깥쪽부터 0으로 시작해서 가장 안쪽까지 1씩 증가하고 제일 마지막은 -1이라고도 한다.

In [3]:
import tensorflow as tf
import numpy as np
import pprint

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

- simple array

In [4]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
pp.pprint(t)
print(t.ndim)
print(t.shape)
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.])
1
(7,)
0.0 1.0 6.0
[ 2.  3.  4.] [ 4.  5.]
[ 0.  1.] [ 3.  4.  5.  6.]


- 2D array

In [5]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim)
print(t.shape)

array([[  1.,   2.,   3.],
       [  4.,   5.,   6.],
       [  7.,   8.,   9.],
       [ 10.,  11.,  12.]])
2
(4, 3)


- shape, rank, axis

In [6]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval() #rank: 1 , shape : 4

array([4])

In [7]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t).eval()  # rank : 2, shape : (2,2)

array([2, 2])

In [8]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval() # rank : 4, shape : (1,2,3,4)

array([1, 2, 3, 4])

- matmul vs multiply

In [10]:
matrix1 = tf.constant([[1., 2.],[3., 4.]])
matrix2 = tf.constant([[1.],[2.]])
print("metrix 1 shape", matrix1.shape)
print("metrix 2 shape", matrix2.shape)
tf.matmul(matrix1, matrix2).eval()

metrix 1 shape (2, 2)
metrix 2 shape (2, 1)


array([[  5.],
       [ 11.]], dtype=float32)

In [12]:
(matrix1*matrix2).eval() #만약 곱하기 연산자를 사용하면 다른 shape이기 때문에 결과는 산으로 간다.

array([[ 1.,  2.],
       [ 6.,  8.]], dtype=float32)

- broadcasting : shape이 다르더라도 연산이 가능하도록 해주는 것이 bradcasting이다.

In [16]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[3.],[4.]])
(matrix1+matrix2).eval()

array([[ 6.,  6.],
       [ 7.,  7.]], dtype=float32)

In [15]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[3., 4.]])
(matrix1+matrix2).eval()

array([[ 6.,  7.]], dtype=float32)

- Reduce mean : 평균 구하기

In [17]:
tf.reduce_mean([1, 2], axis=0).eval()

1

In [18]:
x = [[1., 2.],
     [3., 4.]]
tf.reduce_mean(x).eval()

2.5

In [19]:
tf.reduce_mean(x, axis=0).eval()  (1,3)의 평균, (2,4)의 평균

array([ 2.,  3.], dtype=float32)

In [25]:
tf.reduce_mean(x, axis=1).eval() #(1,2)의 평균, (3,4)의 평균

array([ 1.5,  3.5], dtype=float32)

- Reduce sum : 합에 대한 평균을 구하기

In [21]:
tf.reduce_sum(x).eval()

10.0

In [22]:
tf.reduce_sum(x, axis=0).eval()

array([ 4.,  6.], dtype=float32)

In [23]:
tf.reduce_sum(x, axis=-1).eval()

array([ 3.,  7.], dtype=float32)

In [24]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

- Argmax : 가장 큰 값의 위치를 구하기

In [26]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

In [27]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

- Reshape : 가장 많이 사용하는 것으로 shape을 재생성한다.
      - squeeze : 나누어져 있는 원소를 합친다. 
      - expand : 입력 숫자를 입력 시키고 싶을 때 이용

In [28]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [29]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [30]:
tf.squeeze([[0], [1], [2]]).eval()

array([0, 1, 2])

In [31]:
tf.expand_dims([0, 1, 2], 1).eval()

array([[0],
       [1],
       [2]])

- One hot : 원소 값을 사용하는 것이 아닌 그 자리만 hot 되도록 하여 지정하는 것이다.

In [32]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]],

       [[ 1.,  0.,  0.]]], dtype=float32)

In [34]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval() # 보기 더 좋아짐

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.],
       [ 1.,  0.,  0.]], dtype=float32)

- casting : 데이터의 형식을 바꿔준다.

In [35]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()

array([1, 2, 3, 4])

In [36]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0])

- stack : 입력값을 쌓아서 하나의 배열을 만든다.

In [37]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [40]:
tf.stack([x, y, z], axis=-1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

- Ones and Zeros like : 원소를 0 또는 1로 바꾸고 싶을 때 사용

In [41]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [42]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

- Zip : 모든 원소의 값을 하나로 뭉쳐준다.

In [43]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [44]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
